# 1. Copy this file to the PHPMyadmin prod folder (and rename it in compose.yaml)
# 2. Run the container with : sudo docker compose up -d

services:
  resa_table_pma:
    image: phpmyadmin:5.2.3
    container_name: resa_table_pma
    restart: unless-stopped
    environment:
      PMA_HOST: resa_table_db
      PMA_PORT: 3306
    networks:
      - edge
      - resa_table_internal

networks:
  # Réseau Traefik existant
  edge:
    external: true
    name: edge_edge

  # Réseau interne DB de ResaTable
  resa_table_internal:
    external: true              # Created by the ResaTable compose.prod.yaml file
