name: Build Up and Push prod Images (arm64 and amd64)

on:
  push:
    branches:
    - main

jobs:
# 1. Build arm64 images on self-hosted runner, Deployment on VPS & push on DockerHub
  deploy-vps:
    runs-on: self-hosted
    steps:
      - name: Local build via Docker Compose
        run: |
          cd ~/Projets/ResaTable/ResaTble_php
          git pull origin main
          docker compose -f compose.prod.yml build
          docker compose -f compose.prod.yml up -d --remove-orphans
          docker image prune -f

      - name: Login Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Read version
        id: version
        run: |
          cd ~/Projets/ResaTable/ResaTble_php
          echo "VERSION=$(grep -m1 '^## ' CHANGELOG.md | sed 's/^## //')" >> $GITHUB_OUTPUT

      - name: Push arm64 images on DockerHub
        run: |
          docker tag emiliengibeaud/resa_table:latest emiliengibeaud/resa_table:${{ steps.version.outputs.VERSION }}
          docker push emiliengibeaud/resa_table:latest
          docker push emiliengibeaud/resa_table:${{ steps.version.outputs.VERSION }}

# 1. Build amd64 images on GitHub runner & push on DockerHub
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Login Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Read version
      id: version
      run: echo "VERSION=$(grep -m1 '^## ' CHANGELOG.md | sed 's/^## //')" >> $GITHUB_OUTPUT

    - name: Build and Push amd64 images on DockerHub
      uses: docker/build-push-action@v7
      with:
        context: .
        target: frankenphp_prod
        push: true
        tags: |
          emiliengibeaud/resa_table:latest
          emiliengibeaud/resa_table:${{ steps.version.outputs.VERSION }}
        platforms: linux/arm64
